// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUbbLUB5hoccG0KgoYQtDoqFymUCZmqI',
    appId: '1:22568088380:web:677aa28940c7f39c856439',
    messagingSenderId: '22568088380',
    projectId: 'pemrograman-mobile2-runtime',
    authDomain: 'pemrograman-mobile2-runtime.firebaseapp.com',
    storageBucket: 'pemrograman-mobile2-runtime.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGKwnNmNmpirTobUdgZ8kAKoDsOeCDJh8',
    appId: '1:22568088380:android:5cef2caf9a1d4528856439',
    messagingSenderId: '22568088380',
    projectId: 'pemrograman-mobile2-runtime',
    storageBucket: 'pemrograman-mobile2-runtime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUJ9AbpG_7U5Lq8ECE-UxfMbkBMTF-SVo',
    appId: '1:22568088380:ios:ace86ad05bc72359856439',
    messagingSenderId: '22568088380',
    projectId: 'pemrograman-mobile2-runtime',
    storageBucket: 'pemrograman-mobile2-runtime.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUJ9AbpG_7U5Lq8ECE-UxfMbkBMTF-SVo',
    appId: '1:22568088380:ios:ace86ad05bc72359856439',
    messagingSenderId: '22568088380',
    projectId: 'pemrograman-mobile2-runtime',
    storageBucket: 'pemrograman-mobile2-runtime.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCUbbLUB5hoccG0KgoYQtDoqFymUCZmqI',
    appId: '1:22568088380:web:661148bf43fde9b7856439',
    messagingSenderId: '22568088380',
    projectId: 'pemrograman-mobile2-runtime',
    authDomain: 'pemrograman-mobile2-runtime.firebaseapp.com',
    storageBucket: 'pemrograman-mobile2-runtime.firebasestorage.app',
  );
}
